chars: "abcdefghijklmnopqrstuvwxyz"

window_background_color: "282828"
window_background_opacity: 0.4

label_background_color: "504945"
label_background_opacity: 1.0

focused_background_color: "83a598"
focused_background_opacity: 1.0

label_text_color: ebdbb2

focused_text_color: "282828"

font_family: Jetbrains Mono Nerd Font
font_weight: bold

label_margin_x: 0
label_margin_y: 0

font_size: large

show_confirmation: false
