window_background_color: 1d2021
window_background_opacity: 0.25

label_background_color: 83a598
label_background_opacity: 1.0

label_text_color: 1d2021

font_family: Jetbrains Mono Nerd Font
font_weight: bold
